apiVersion: batch/v1beta1
kind: CronJob

metadata:
  name: nats-pub-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: nats-pub
      name: nats-pub
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: nats-pub
              image: localhost:32000/natpub
              resources:
                limits:
                  cpu: "100m"
                  memory: "50Mi"
              command: [ "/nats-pub" ]
              args: [ "-s" , "nats://my-nats:4222",  "-c",  "msg.test" ]
      backoffLimit: 1