apiVersion: apps/v1
kind: Deployment

metadata:
  name: nats-sub-deployment
spec:
  selector:
    matchLabels:
      app: nats-sub
  template:
    metadata:
      labels:
        app: nats-sub
      name: nats-sub
    spec:
      containers:
        - name: nats-sub
          image: localhost:32000/natsubs
          resources:
            limits:
              cpu: "100m"
              memory: "50Mi"
          command: ["/nats-sub"]
          args: [ "-s" , "nats://my-nats:4222", "msg.test"]
